Ra 03
Artur-star/RecipesApp pull request #1
Opened 2024-08-10 13:48 UTC by Artur-star

2024-08-10 13:54 UTC, Artur-star commented
Не получается изменить основной цвет кнопок и не получается правильно расположить иконку heart внутри кнопки "Избранное"

2024-08-11 11:13 UTC, ievetrovdev commented
Нейминги коммита, пулл реквеста и ветки следует делать все в едином стиле (который принят в сообществе). Как правило это аббревиатура название проекта.

Например:
RA-03 create navigation buttons (для названия PR и сообщения коммита)
RA-03-create-navigation-buttons (для названия ветки, разделение всех слов дефисами)

2024-08-11 11:20 UTC, ievetrovdev requested changes

2024-08-11 11:20 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:background="@drawable/shape_button_rounded_blue"
На этом этапе Shape Drawable нам не понадобится. Скругленные углы задаются кнопка через стиль. Например, <item name="cornerRadius">@dimen/main_space_half_8</item>

2024-08-11 11:20 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_marginStart="4dp"
Все значения не забываем выносить в ресурсы и переиспользовать. Размеры элементов/шрифтов, цвета, строки

2024-08-11 11:20 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="main_layout">#F4FAFF</color>
для кастомных цветов предлагаю такой формат названия ресурсов, например category_color. "color" в конце обязательно для отделения одного айди ресурса от другого.

2024-08-11 11:20 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="category">Категории</string>
Чтобы при глобальном поиске какой-то строки кода не попадали все значения в кучу, которые включают слово category – стоит для идентификатора этой строки сделать какое-то более общее название. Например, так title_categories. Это одна из причин. И в дальнейшем этот ресурс использовать и для заголовка экрана с категориями в шапке.

2024-08-11 11:20 UTC, ievetrovdev commented on app/src/main/res/values/style_nav_button.xml
> +        <item name="android:paddingVertical">10dp</item>
значения размеров выносим в ресурсы

2024-08-11 11:20 UTC, ievetrovdev commented on app/src/main/res/values/style_nav_button.xml
> +    <style name="StyleNavButton" parent="Widget.Material3.Button">
Новый стиль нужно разместить в файле styles, в теге style. А не в отдельном xml

2024-08-11 11:20 UTC, ievetrovdev commented on app/src/main/res/values/themes.xml
> +        <item name="android:statusBarColor">@color/white</item>
Цвет установлен корректно, однако, теперь белое на белом сливается. Есть еще один специальный атрибут, который говорит системе, что это светлый статус/навбар и что шрифт нужно сделать серым.

2024-08-14 08:38 UTC, ievetrovdev commented
Еще раз

Нейминги коммита, пулл реквеста и ветки следует делать все в едином стиле (который принят в сообществе). Как правило это аббревиатура название проекта.

Например:
RA-03 create navigation buttons (для названия PR и сообщения коммита)
RA-03-create-navigation-buttons (для названия ветки, разделение всех слов дефисами)

2024-08-14 08:47 UTC, ievetrovdev requested changes
Иконка все еще не установлена (не отображается при запуске на сплеш скрине). Используй инструкцию из ТЗ "1. Использование функции 'New Image Asset'" для корректного добавления растрового изображения

2024-08-14 08:47 UTC, ievetrovdev commented on app/src/main/res/values/themes.xml
> +        <item name="android:statusBarColor">@color/white</item>
Само значение цвета отличается от того, что в макете задается как фоновый. На запущенном приложении это ярко выражено
<img width="117" alt="Снимок экрана 2024-08-14 в 11 40 22" src="https://github.com/user-attachments/assets/fb4415f7-f882-4aca-89f3-e9ea358c6872">

2024-08-14 08:47 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14sp</item>
размер шрифтов тоже выносим в ресурсы

2024-08-14 08:47 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="favourites">Избранное</string>
по аналогии нужно переименовать айдишний для этой строки

2024-08-14 08:47 UTC, ievetrovdev commented on app/src/main/res/drawable/shape_button_rounded_red.xml
эти файлы теперь не используются - удаляем

2024-08-14 08:47 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +            android:id="@+id/button"
Если задаешь айдишники для вью – корректнее делать их релевантными. Например, btnCategories. Для второй кнопки аналогично.

2024-08-14 08:47 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="main_padding">16dp</dimen>
Хорошо, добавлю еще. Стиль названия ресурсов в приложении обычно скорее придумывается, чем берется како-либо эталонный стиль. Существуют разные подходы.

Можно в названии писать цифру в конце, которая означает размер, а можно использовать такую структуру, например:
margin_small_x">10dp
margin_small_xx">12dp 
margin_small_xxx">14dp
margin_normal">16dp
margin_normal_x">18dp
margin_normal_xx">20dp
margin_normal_xxx">22dp

2024-08-17 12:07 UTC, Artur-star commented
> Еще раз
> 
> Нейминги коммита, пулл реквеста и ветки следует делать все в едином стиле (который принят в сообществе). Как правило это аббревиатура название проекта.
> 
> Например: RA-03 create navigation buttons (для названия PR и сообщения коммита) RA-03-create-navigation-buttons (для названия ветки, разделение всех слов дефисами)

А что необходимо сделать исправить первый самый коммит

> Еще раз
> 
> Нейминги коммита, пулл реквеста и ветки следует делать все в едином стиле (который принят в сообществе). Как правило это аббревиатура название проекта.
> 
> Например: RA-03 create navigation buttons (для названия PR и сообщения коммита) RA-03-create-navigation-buttons (для названия ветки, разделение всех слов дефисами)

Исправил название Pull Request

2024-08-18 10:01 UTC, ievetrovdev commented
> Исправил название Pull Request

Не совсем. для аббревиатуры надо обе заглавные буквы от названия приложения. RecipesApp

<img width="316" alt="Снимок экрана 2024-08-18 в 13 01 03" src="https://github.com/user-attachments/assets/8f219982-9e78-4462-b758-48aa97ba761f">

2024-08-18 10:07 UTC, ievetrovdev requested changes

2024-08-18 10:07 UTC, ievetrovdev commented on app/src/main/res/values/ic_launcher_background.xml
> +<resources>
а этот ресурс что означает?

2024-08-18 10:07 UTC, ievetrovdev commented on app/src/main/res/values/dimens.xml
> +    <dimen name="font_size_14">14sp</dimen>
лучше визуально разделять шрифт от других размеров

2024-08-18 10:07 UTC, ievetrovdev commented on app/src/main/res/values/themes.xml
> +        <item name="android:statusBarColor">@color/white</item>
Согласно ТЗ эти области (статус и нав) должны быть цвета основного фона

2024-08-18 10:07 UTC, ievetrovdev commented on app/src/main/res/layout/activity_main.xml
> +        android:weightSum="2"
weightSum можно не использовать, если у потомков одинаковый вес. Все будет посчитано корректно.

2024-08-19 12:10 UTC, ievetrovdev approved these changes

2024-08-19 14:56 UTC, merged