RA-17 Save recipe in SP
Artur-star/RecipesApp pull request #15
Opened 2024-10-17 16:28 UTC by Artur-star

2024-10-17 16:30 UTC, Artur-star commented
Не могу понять как реализовать логику пункта 6 и 7, остальное вроде сделал, Подсоби пожалуйста

2024-10-18 16:51 UTC, Churickoid commented
> Реализовать логику получения избранных id из хранилища. Проверять наличие id текущего рецепта в списке избранных и в зависимости от результата отображать соответствующую иконку при инициализации фрагмента.

При входе на фрагмент мы должны вызывать getFavorites() и обновлять статус кнопки относительно того находиться ли этот id в списке или нет.

>Реализовать логику добавления элемента и его удаления из хранилища по клику на иконку 'Избранное'. Использовать ранее объявленные методы для взаимодействия с SP.

При нажатии на кнпоку получать актуальный список  getFavorites(), в зависимости от состояния кнопки убирать элемент из списка или добавлять его в список, в конце сохранять через saveFavorites отредаченный список

Отдельный метод deleteFavorites как таковой не нужен

2024-10-18 19:27 UTC, Churickoid requested changes

2024-10-18 19:27 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +            flag = !flag
Если ты делаешь в самом начале условия отрицание !flag, то тогда лучше эту строку перенести в самое начало и уже передавать в условие просто flag

2024-10-18 19:27 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/Constants.kt
> +const val PREFS_KEY_FAVORITES_CATEGORY = "favoritesCategory"
Неправильно, когда консанты лежат просто в файле, без обертки в object Constants. Их уровень видимости становится глобальным, так при быстром наборе они будут постоянно всплывать. Если таких констант в проекте будет 1000, то они захламлят весь быстрый набор.
Оберни их в objects Constants{}

2024-10-18 19:27 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/Constants.kt
> +const val PREFS_KEY_FAVORITES_CATEGORY = "favoritesCategory"
![image](https://github.com/user-attachments/assets/56fd5239-1c6e-4ceb-b375-d27e8db284ee)

2024-10-18 19:27 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +                getFavorites().add(recipe?.id.toString())
Ты получаешь новый список, но он никуда не сохранется, следоавтельно - ничего не происходит. Сохраняй новый список в переменную и передавай дальше в save его.

Проверить корректную работу можешь самостоятельно, поверни экран в гаризонтальное положение и обратно - иконка должна сохранить своё состояние. При повороте экрана onCreate повторно отрабатывает

2024-10-18 19:27 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +                getFavorites().remove(recipe?.id.toString())
тоже самое

2024-10-18 19:27 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +    private fun setIconHearth(): Boolean {
Немного непонятное решение, изменение иконки и сохранение нового списка происходят при одном стейте. Почему решил вынести половины смены стейта в отдельную функцию? 
Мне кажется гораздо удобнее читается, когда меняется только флаг, а в зависимости от этого выполняются действия: изменение иконки и списка. А сейчас  половина действий и изменение флага в одной функции, а потом другая половина действий выполняется и зависит от резлуьтата  прошлой функции. Очень замудрено

2024-10-19 06:44 UTC, Artur-star commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +                getFavorites().add(recipe?.id.toString())
Я проверил, да, действительно не сохраняется список при повороте, либо при полном закрытии, но я пока решил не создавать отдельную переменную, как ты сказал, а добавить сначала edit.clear в метод saveFavorites, ведь нужно удалять старый список перед сохранением нового и все заработало, то есть я не создавал отдельную переменную set, а напрямую работал с getFavorites, как мне показалось в методах saveFavorites и getFavorites наш список связан ключом PREFS_KEY_FAVORITES_CATEGORY, поэтому когда мы сохраняем список в saveFovorites, мы работаем со список который был создан в getFavorrites, также смотрел через Log

2024-10-19 06:50 UTC, Artur-star commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +    private fun setIconHearth(): Boolean {
Здесь решил создавать новую функцию для избежания дублирования конструкции if else, все исправил

2024-10-19 07:11 UTC, Artur-star commented
и еще заметил, при повороте экрана шапка статична, и тем самым перекрывает весь обзор RecyclerView, кроме активити, где реализован SeekBar, как исправить?

2024-10-19 11:11 UTC, Churickoid commented
> и еще заметил, при повороте экрана шапка статична, и тем самым перекрывает весь обзор RecyclerView, кроме активити, где реализован SeekBar, как исправить?

У тебя длина шапки в xml прописана на определенную длину.  Так прописан курс, чтобы не ломать верстку можешь сделать отдельные экраны для горизонтальной ориентации в студии с другими прописанными значениями
![image](https://github.com/user-attachments/assets/19d3755b-4920-48e6-8e8f-d3fa04190168)

2024-10-19 11:43 UTC, Churickoid requested changes

2024-10-19 11:43 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +            saveFavorites(setFavorites)
А зачем при первой отрисовки стейта вообще менять sharedPreferences? Мы же просто получаем актуальное состояние и отрисовываем по нему кнопку. Это здесь лишнее

2024-10-19 11:43 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +    private var setFavorites: MutableSet<String> = HashSet()
Такой глобальный список делать не надо, у тебя может спокойно возникнуть ситуация, когда этот список может отличаться от списка из шаред преференсис. Зачем нам усложнять себе жизнь и следить за двумя списками сразу?
В прошлой реализации ты получал список, модернизировал его, а потом ты снова запрашивал новый список, неотредактированный, и сохранял его. Я предложил добавить локальное хранение списка и передавать его дальше.
![image](https://github.com/user-attachments/assets/3f0d8ead-c74d-47a2-b942-4b0cbc6442df)

Такой глобальный список - плохая идея. Я лишь предложил добавить
 val favorites = getFavorites.add(recipe?.id.toString())
 saveFavorites(favorites)

2024-10-19 11:43 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +        val edit = sharedPrefs.edit()
переменная edit здесь лишняя, можно всё выполнить без неё
```
sharedPrefs.edit()
.putStringSet(PREFS_KEY_FAVORITES_CATEGORY, recipeId)
.apply()
```

2024-10-19 11:43 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +        edit.clear()
Очищать префы точно не надо, у тебя могут лежать в префах значения по другим ключам, ты их все сотрешь здесь. Проблема связана с глобальным списком. Надо глянуть код после избавления от него, это может и работает сейчас, но это не решение проблемы

2024-10-19 11:50 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +        val sharedPrefs = requireContext().getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
Шаред преференсис всегда один и тот же объект, каждый раз его искать через контекст - лишнее действие. Давай вынесем его в отдельную переменную

2024-10-19 15:49 UTC, Artur-star commented
![image](https://github.com/user-attachments/assets/ad4db227-bfa8-4edc-b990-984eaf62f179)
Такая строка не получается, ведь add возвращает boolean, создал локальную переменную val favorites = getFavorites(), убрал полную очистку базы, но проблему не удается устранить, при закрытии приложения база не восстанавливается

2024-10-19 15:52 UTC, Artur-star commented
А дальше по курсу мы будем добавлять горизонтальную ориентацию экрана?

2024-10-19 19:51 UTC, Churickoid commented
> А дальше по курсу мы будем добавлять горизонтальную ориентацию экрана?

Нет, в курсе такого нет

2024-10-19 19:52 UTC, Churickoid commented
> ![image](https://private-user-images.githubusercontent.com/55159022/378098996-ad4db227-bfa8-4edc-b990-984eaf62f179.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNjc1MDgsIm5iZiI6MTcyOTM2NzIwOCwicGF0aCI6Ii81NTE1OTAyMi8zNzgwOTg5OTYtYWQ0ZGIyMjctYmZhOC00ZWRjLWI5OTAtOTg0ZWFmNjJmMTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE5NDY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4YjE1NjQwYjI0OTE0OTZlOWM4YTZjZjIwYjM0MTk2ZTc0YjdlODI4MmNjOTU0YWMyZGExNzYzMzc2MzI4MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JAWHCvSN5rBnQFl3lu5LYo5Fg0ZTL6SgwzVKIVZDa68) Такая строка не получается, ведь add возвращает boolean, создал локальную переменную val favorites = getFavorites(), убрал полную очистку базы, но проблему не удается устранить, при закрытии приложения база не восстанавливается

Тогда поменять местами надо, сначала присвоение к val favorites = getFavorites()
favorites.add(recipe?.id.toString())
saveFavorites(favorites)
это не проблема

2024-10-19 19:56 UTC, Churickoid commented
Ты не выложил новых коммитов.
Избавься полностью от глобального списка.
private var setFavorites: MutableSet<String> = HashSet()
 Если проблема не уйдет, то надо уже смотреть в исправленном коде и дебажить

2024-10-20 14:16 UTC, Churickoid requested changes

2024-10-20 14:16 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +    private lateinit var sharedPref: SharedPreferences
lateinit не рекомендуется использоваться, при неправильном стейте оно может поломать приложение.  Пределагаю перенести инициализация из onViewCreated в by lazy, так экземпляр создатся в момент орбащения к нему

2024-10-20 14:16 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipeFragment.kt
> +        return favorites
Проблема с иконкой после перезапуска связана с тем, что ты возвращаешь список из sharedPref, в задании прописано, что итоговый список надо обернуть в HashSet(favorites), так ты явно говоришь системы, что ты создал новую ячейку в памяти и не будет проблем с редактирыванием этого элемента и сохранением в последствии.

Из задания
https://developer.android.com/reference/android/content/SharedPreferences#getStringSet(java.lang.String,%20java.util.Set%3Cjava.lang.String%3E)
Note that you must not modify the set instance returned by this call. The consistency of the stored data is not guaranteed if you do, nor is your ability to modify the instance at all.

2024-10-20 16:00 UTC, Artur-star commented
Все поправил по заданию, пока горизонтальную настройку не буду трогать, в горизонтальной шапка выглядеть будет не очень. В горизонтальной может вообще стоит image шапки убрать и оставлять 
только текст, так делают?

2024-10-20 16:18 UTC, Churickoid approved these changes
Все верно, молодец! Лучше не убирать ничего, как быстрое решение предлагаю перенести шапку рецепта в scrollView, так можно будет её просто проскролить и не придется создавать отдельный экран для лэйаута

2024-10-20 17:59 UTC, Churickoid approved these changes

2024-10-21 05:07 UTC, merged