RA-18 Implement favorites screen
Artur-star/RecipesApp pull request #16
Opened 2024-10-22 14:55 UTC by Artur-star

2024-10-22 20:02 UTC, Churickoid requested changes

2024-10-22 20:02 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/FavoritesListFragment.kt
> +    private val recipesListFragment = RecipesListFragment()
Создавать экземпляры других врагментов внутри фрагмента крайне опасно. Это и приводит к крэшу. Ты пытаешься поулчить внутри recipeFragment SharedPreferences, которые смогут создастся после инициализации context. Это происходит в методе onCreate, но у этого фрагмента он не вызовется, тк он не учавствует в UI никак. 
Все фрагменты должны быть изолированы и не зависить от жизненного цикла друг друга.
Единственный приемлимый способ - дёргать методы из componion object. Но там все объекты изолированы, те же sharedPreferences придется передавать в аргументы функции.

2024-10-22 20:02 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/fragments/FavoritesListFragment.kt
> +            STUB.getRecipesByIds(recipeFragment.getFavorites().map { it.toInt() }.toSet())
Щас надо избавиться от влияния других фрагментов в коде. Сокращать дублирование кода не так, через продумывание слоёв и архитектуры. Этим мы будем заниматься дальше.  
Если прям сильно хочется не дублировать создать отдельный  object SharedPreferencesUtils и используй его методы в двух фрагментах.  Но придется все нужные фрагменты передавать в аргументы

2024-10-23 19:22 UTC, Churickoid approved these changes
Всё верно! Молодец!

2024-10-24 04:07 UTC, merged