RA-22 Subscribe LiveData
Artur-star/RecipesApp pull request #18
Opened 2024-11-04 07:12 UTC by Artur-star

2024-11-04 08:14 UTC, Artur-star commented
Привет, в целом понял как работает ViewModel и LiveData, но конкретно в данном уроке не могу разобраться, мы в RecipeFragment создаем поле viewModel и делегируем его во viewModels, для чего? В методе onViewCreated используем observe(viewLivecycleOwner), не совсем понял отличие от (this), viewLivecycleOwner смотрим ЖЦ конкретной view, а this всего фрагмента, в данной задаче viewLivecycleOwner на что конкретно смотрит?

2024-11-04 17:49 UTC, aGroupoid commented
> конкретно в данном уроке не могу разобраться, мы в RecipeFragment создаем поле viewModel и делегируем его во viewModels, для чего?

1)  Если повернуть экран, то фрагмент уничтожится и создастся его копия. Для сохранения состояния экрана и придумали ViewModel, которая не пересоздается и существует только единственная его копия. Делегирование через by viewModels под копотом сохраняет в кэш памяти созданную версию и отдаёт её при пересоздании фрагмента.

> вместо этой конструкции мы делаем делегирование? 

2) Если глянешь под копотом by viewModels(), то увидишь, что под копотом вызывается эта конструкция, просто Котлин позволяет через синтаксический сахар оформить эту логику проще. Твоя конструкция, которую ты скинул, создана только для использования в Джава коде, поскольку там нету ключевого слова by.
![image](https://github.com/user-attachments/assets/a084f453-e4ad-415c-a4c1-55f3e2ba8d63)

> В методе onViewCreated используем observe(viewLivecycleOwner), не совсем понял отличие от (this), viewLivecycleOwner смотрим ЖЦ конкретной view, а this всего фрагмента, в данной задаче viewLivecycleOwner на что конкретно смотрит?

3) Жизненный цикл фрагмента намного больше, чем его view. У view фрагмента начинается жизнь с onViewCreated и заканчивается onViewDestroyed. У фрагмента он побольше, а кроме как менять view на observer и нужен. После удаления view нам дальше следить за ним нет смысла. Поэтому мы и не передаем сам фрагмент this.

> Блок init вызывается же при первой инициализации объекта ViewModel, но у меня не вызывается этот блок, значит не происходит инициализация?

4) Я глянул, у тебя вызывается один раз лог внутри init. При повороте он не будет это делать, поскольку он сохраняется. При создании нового фрагмента рецептов он вызовется повторно

2024-11-04 17:49 UTC, Churickoid requested changes

2024-11-04 17:49 UTC, aGroupoid commented on app/src/main/res/layout/fragment_recipe.xml
> +                android:id="@+id/isFavorite"
Лучше вернуть нейминг как было. Id должно описывать вьюху, текущий нейминг ничего не говорит о ней

2024-11-04 17:49 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeViewModel.kt
> +        mutableRecipeStateLD.value = RecipeState(true)
Чтобы прошлый стейт не перетерся, всегда нужно менять значение через .copy(). Если бы у тебя щас лежал Recipe, то он бы перетерся и заменился дефолтным null

2024-11-04 17:49 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeViewModel.kt
>      val isFavorite: Boolean = false,
Не хватает в стейте параметра, отвечающего за количество порций

2024-11-04 17:49 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeViewModel.kt
> +    private var mutableRecipeStateLD = MutableLiveData<RecipeState>()
принято называть приватную переменную _recipeStateLD, так легко их различать.
Также пропиши ей val, сама liveData не меняется, только значение внутри неё

2024-11-05 18:53 UTC, Churickoid approved these changes
Молодец, всё верно!

2024-11-06 03:20 UTC, merged