RA-23 getting recipe in VM
Artur-star/RecipesApp pull request #19
Opened 2024-11-07 18:31 UTC by Artur-star

2024-11-07 18:36 UTC, Artur-star commented
Не могу разобраться в отображении иконки isFavorite. Recipe в избранное добавляется, но imageButtom isFavorite показывает что выключена. Пытаюсь понять каким образом вызывается observe, но без успешно

2024-11-07 19:20 UTC, Churickoid requested changes

2024-11-07 19:20 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeViewModel.kt
> +        RecipeState(
Мы должны присвоить этот созданный стейт _recipeStateLD.value. Сейчас по сути ничего не происходит. Чтобы прошлый стейт не затерся - мы должны его присваивать через .copy() и менять только ту часть стейта, которая затрагивается этой функцией. В данном случае countPortions нужно опустить, иначе при повороте экране вызовется fragment.onCreate -> loadRecipe -> countPortions = 1, этот параметр стейта сбросится надефолтный

2024-11-07 19:20 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeFragment.kt
> +            viewModel.onFavoritesClicked(recipe?.id ?: 0)
Сама кнопка должна вызывать только метод из viewModel, всё остальное должно происходить во viewModel. Всё что связано с ui - перенесити в observer и менять состояние кнопки от нового стейта, который пришел в it.

2024-11-07 19:20 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeFragment.kt
> +            flag = it.isFavorite
Суть observer такая, что при изменении LiveData будет вызываться всё то, что написано внутри фигурных скобок observer, с актуальными данными из стейта внутри.
Мы не должны создавать во фрагменте отдельные переменные, поскольку они ничего не сделают. Переменная поменяется, но весь ui уже отрисовался в методе onViewCreated, никакой реакции не будет. Мы должны именно перенести те строки, которые меняют состояние кнопки, ссылаясь на актуальные данные в it.

2024-11-07 19:20 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeFragment.kt
> +            recipe = it.recipe
с recipe аналогично, все view которые зависят от актуального состояния recipe нужно перенести в observer

2024-11-08 21:21 UTC, Churickoid approved these changes
Молодец! Всё верно исправил

2024-11-08 21:21 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeFragment.kt
> +            val recipe = it.recipe
В лямбде сверху можно переименовать it во что угодно, таким способом: recipeState ->.
Можно пойти дальше и указать через скобки сразу каждую из переменных таким образом (flag,_,recipe) ->. А эти строки иницилазии убрать

2024-11-09 03:18 UTC, merged