RA-26 Refactor init RecyclerView
Artur-star/RecipesApp pull request #22
Opened 2024-11-11 09:49 UTC by Artur-star

2024-11-11 10:00 UTC, Artur-star commented
Не совсем понял суть изменения и видимости dataset, если мы инициализируем IngedientAdapter и MethodAdapter не внутри обозревателя LiveData, а только при создании фрагмента, хотя в таске написано "В эти свойства созданных объектов будут приходить данные каждый раз при изменении стейта. До этого они приходили один раз при инициализации адаптеров."
![image](https://github.com/user-attachments/assets/12d05967-fecb-496c-b93c-1a2d3d244204)

2024-11-11 21:03 UTC, Churickoid requested changes

2024-11-11 21:03 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeFragment.kt
> +        onChangeIngredients(p1)
Если ты используешь параметр, давай им понятный нейминг.  p1 трудно воспринимать

2024-11-11 21:03 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/ui/resipes/recipe/RecipeFragment.kt
>              binding.rvMethod.adapter = methodAdapter
Раньше работа с адаптерами была верной, просто ты сделал это раньше. Верни в наблюдателя observer как было, в задании так и требовалось. 
Порекомендовал бы еще привязывать адаптер к ресайклер вью только один раз и не создавать каждый раз новый объект Адаптера. Правильнее будет создать переменные адаптера на уровне класса, изначально с пустым списком.  Потом вне наблюдателя привязать адаптер к ресайкл вью. А в самом observer уже менять данные и уведомлять ресайклер вью через notifyDataSetChanged о изменении списка, чтоб он перерисовался.
А сейчас создается множество новых объектов адаптеров, это работает, но не очень оптимизировано

2024-11-12 05:28 UTC, Artur-star commented
Все поправил, я присваиваю новое значение dataset в методах update..., соответственно создается новый конструктор и заново выполняется класс Adapter'a, хотел спросить почему если я пишу внутри observe { ingredientAdapter = IngredientsAdapter(recipe?.ingredients ?: emptyList()) } а в методе updateIngredient в параметрах не прописываю recipe?.ingredients ?: emptyList(), то у меня создается пустой список Ingredient'ов?

2024-11-12 17:17 UTC, Churickoid approved these changes
Всё верно, молодец!

2024-11-12 17:31 UTC, merged