RA-27 Add ViewModel for all screens
Artur-star/RecipesApp pull request #23
Opened 2024-11-13 14:51 UTC by Artur-star

2024-11-14 13:06 UTC, Churickoid requested changes

2024-11-14 13:06 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/recipesList/RecipesListFragment.kt
> +            binding.rvRecipes.adapter = listAdapter
Каждый раз создавать и прилинковывать новый объект Адаптера - плохая практика. Нужно прилинковывать к Ресайклер Вью один раз, и менять dataSet одного и того же Адаптера, по аналогией с порциями в прошлом пр.

Поправь это везде

2024-11-14 13:06 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/recipesList/RecipesListViewModel.kt
> +class RecipeListViewModel(application: Application, private val state: SavedStateHandle) :
переименуй лучше стейт в savedStateHandle или что-то похоже.  Просто у нас сейчас есть стейт RecipeListState, по неймингу кажется что это связано с ним

2024-11-14 13:06 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/recipesList/RecipesListViewModel.kt
> +        val categoryId = state.get<Int>(ARG_CATEGORY_ID)
Молодец, что берешь через механизм savedStateHandle сразу на уровне viewModel. Но давай добавим еще в state поле categoryName и будем также его менять через observer, а не напрямую во фрагменте. Это будет более правильно по MVVM патерну

2024-11-14 13:06 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/favorites/FavoritesListViewModel.kt
> +                .getSharedPreferences(Constants.PREFS_NAME, Context.MODE_PRIVATE)
При повороте экрана фрагментов всегда будет вызыватсья getFavorites и создаваться sharedPreferences новый экземпляр, давай вынесем в отдельную  переменную sharedPreferences

2024-11-14 13:06 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/favorites/FavoritesListFragment.kt
> +            binding.rvFavorites.adapter = adapter
Проблема с адаптером, писал в другом комменте. Создай отдельную переменную с адаптером, по дефолту пустой список. Меняй только её dataSet через функцию

2024-11-14 13:06 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/favorites/FavoritesListFragment.kt
> +                adapter.setOnItemClickListener(object : RecipesListAdapter.OnItemClickListener {
Адаптер никак не зависит от данных стейта, вынеси его из observer

2024-11-14 17:37 UTC, Churickoid requested changes

2024-11-14 17:37 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/adapters/RecipesListAdapter.kt
> +        this.dataSet = dataSet
Без notifyDataSetChanged ресайклер вью не поймет, что надо обновляться.  Сейчас это работает, только из-за синхронной работы кода

2024-11-14 17:37 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/favorites/FavoritesListViewModel.kt
> +    private val sharedPreferences = getFavorites()
sharedPreferences это не MutableSet<String>, а SharedPrefrences. Вынести нужно только создание этого объекта getApplication<Application>()
                .getSharedPreferences(Constants.PREFS_NAME, Context.MODE_PRIVATE)

2024-11-14 17:37 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/recipesList/RecipesListViewModel.kt
> +        val categoryName = savedStateHandle.get<String>(ARG_CATEGORY_NAME)
По итогу мы импортируем почти всю сущность category, только раздробленную. Давай как в одном из прошлых ПР будем передавать Parcelable сразу, код станеет компактнее и проще

2024-11-15 16:55 UTC, Churickoid approved these changes
Всё верно, молодец!

2024-11-15 16:55 UTC, Churickoid commented on app/build.gradle.kts
> +        targetSdk = 33
Почему решил понизить targetSdk? Приложение должно быть ориентировано на самую актуальную версию

2024-11-15 17:24 UTC, merged