RA-30 Implement transition animations
Artur-star/RecipesApp pull request #26
Opened 2024-11-29 04:52 UTC by Artur-star

2024-11-29 20:33 UTC, Churickoid requested changes
Сейчас нету анимации у экранов при нажатии на кнопки из Activity.  Добавь в navOptions блок anim{} и пропиши внутри те же значения

2024-11-29 20:33 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/categories/categoryList/CategoriesListFragment.kt
> +            CategoriesListFragmentDirections.actionCategoriesListFragmentToRecipesListFragment2(
Странная двойка на конце, давай уберем

2024-11-29 20:33 UTC, aGroupoid commented on app/src/main/java/com/knyazev/recipesapp/ui/categories/categoryList/CategoriesListFragment.kt
> +        }
Сейчас нарушается принцип MVVM, вся работы с данными должна происходить внутри viewModel. Мы целую категорию можем получить сразу внутри адаптера. Давай перепишем onClickListener чтоб он возвращал не айдишник, а весь рецепт. Тогда нарушение пропадёт

2024-11-30 18:05 UTC, Churickoid approved these changes
В целом всё ок, молодец! Поправь в следующем  пр небольшой коммент

2024-11-30 18:05 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/ui/recipes/recipesList/RecipesListFragment.kt
> +                .build()
Неправильно ты понял коммент. Во фрагментах navOptions добавлять не надо, все эти настройки прописаны в actionRecipesListFragmentToRecipeFragment.
У нас экшены не используются только на уровне MainActivity, там и нет анимации. Нужно добавить код блок anim{} в эти места. Именно через anim{}, текущаяя реализация устаревшая
<img width="731" alt="Снимок экрана 2024-11-30 в 21 04 15" src="https://github.com/user-attachments/assets/ad4a5dc5-3e51-46be-9adf-58d1621bb9a1">

2024-11-30 18:05 UTC, Churickoid commented on app/src/main/java/com/knyazev/recipesapp/ui/categories/categoryList/CategoriesListFragment.kt
> +                openRecipesByCategoryId(category)
из нейминга тоже убери Id

2024-12-01 03:31 UTC, merged