RA-05 Basic navigation settings
Artur-star/RecipesApp pull request #3
Opened 2024-08-27 14:01 UTC by Artur-star

2024-08-27 20:08 UTC, ievetrovdev commented
Возвращаясь к прошлым ПР, иконка отличается от той, что на макете (сплющена). Попробуй выгрузить из Фигмы вместе со фреймом

2024-08-28 17:21 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/MainActivity.kt
> +            if (savedInstanceState == null) {
Попробуй перевернуть экран и после этого переключить кнопки. SavedInstanceState уже будет не null, поскольку Activity уже было когда-то создано и код внутри условия выполняться не будет

2024-08-28 17:21 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/FavoritesFragment.kt
> +    ): View? {
Метод onCreateView в Kotlin не может вернуть null, поэтому возврающий тип можно смало ставить View. Такое часто случается при работе с Java-методами в Kotlin, поскольку в Java любая переменная является nullable. Обрати внимание, что сама студия подсвечивает это ворнингом

2024-08-28 17:21 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/MainActivity.kt
> +            if (savedInstanceState == null) {
При старте приложения никакой из фрагментов не отображется

2024-08-28 17:21 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Неиспользуемая строка

2024-08-29 15:16 UTC, Artur-star commented
> Возвращаясь к прошлым ПР, иконка отличается от той, что на макете (сплющена). Попробуй выгрузить из Фигмы вместе со фреймом

![image](https://github.com/user-attachments/assets/21037b58-9385-48ac-af45-ea9b351b0503)

Я вот так сделал export в формате png, пробую очистить все форматы иконки из проекта, не получается

2024-08-30 18:25 UTC, ievetrovdev commented
> > Возвращаясь к прошлым ПР, иконка отличается от той, что на макете (сплющена). Попробуй выгрузить из Фигмы вместе со фреймом
> 
> Я вот так сделал export в формате png, пробую очистить все форматы иконки из проекта, не получается

С иконкой приложения все в порядке, речь идет об иконке сердечка на кнопке изрбанном

2024-08-30 18:49 UTC, ievetrovdev requested changes

2024-08-30 18:49 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/MainActivity.kt
> +                addToBackStack(null)
Самый первый фрагмент лучше не класть во в backStack, поскольку при нажатии назад, мы попадаем в состояние без фрагментов с пустым экраном

2024-09-01 17:09 UTC, ievetrovdev approved these changes
Апрувлю, осталась нектричная ошибка, цвет кнопки Избранного не соответсвтует дизайну. Поправь уже в следующей задачке

2024-09-02 12:28 UTC, merged