RA-08 Implementation recycler view with list categories
Artur-star/RecipesApp pull request #6
Opened 2024-09-11 11:25 UTC by Artur-star

2024-09-12 20:58 UTC, ievetrovdev requested changes
Почему то первым экраном открывается фрагмент не с категориями, а favorites

2024-09-12 20:58 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="image_of_categories">Image of categories</string>
Строковые файлы используются не только для удобного переиспользования строк, но и для массовой локализации. В основном файле данных хранятся на основном языке, но еще добавляются дополнительные каталоги с определенными квалификаторами. Например, чтобы создать файл с такими же строками на английском языке создается новый каталог в папке res с названием values-en.

Приложение будет смотреть на установленный язык в операционной системе и брать строки из соответствующего каталога. Если подходящего каталога не найдется – будут браться строки из основного values. Подробнее https://developer.android.com/guide/topics/resources/localization

2024-09-15 10:11 UTC, ievetrovdev commented
Сейчас при нажатии на карточку нету никаких эффектов.
Есть простой набор атрибутов, чтобы ripple эффект для элемента cardView заработал:
android:foreground = "?selectableItemBackground"
android:clickable = "true"
android:focusable = "true"

2024-09-15 10:25 UTC, ievetrovdev requested changes

2024-09-15 10:25 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/CategoriesListAdapter.kt
> +    class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
Давай сразу во viewHolder передавать binding. В первую очередь это сократит код и улучшит его читаемость.

2024-09-15 10:25 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/CategoriesListAdapter.kt
> +
СontentDescription используется для предоставления текстового описания для не текстовых элементов, таких как изображения, кнопки с иконками и других графических объектов.

Для изображений элементов категорий тоже следует добавить описание. Причем подход  рекомендую через адаптер – чтобы у каждого элемента было свое описание.

У viewHolder.imageView есть специальная переменная contentDescription

2024-09-15 10:25 UTC, ievetrovdev commented on app/src/main/res/values/strings.xml
> +    <string name="image_of_categories">Image of categories</string>
Не забудь добавить перевод для этог поля тоже

2024-09-15 14:16 UTC, Artur-star commented on app/src/main/res/values/strings.xml
> +    <string name="image_of_categories">Image of categories</string>
Перевод Image of categories добавлена в values-ru

2024-09-16 09:29 UTC, ievetrovdev reviewed
Молодец, всё правильно!

2024-09-16 09:30 UTC, ievetrovdev approved these changes

2024-09-16 17:05 UTC, merged