RA-10 Transfer data to recipe screen via Bundle
Artur-star/RecipesApp pull request #8
Opened 2024-09-22 07:11 UTC by Artur-star

2024-09-22 07:14 UTC, Artur-star commented
При клике на категорию не открывает экран со списком рецептов, что я не доделал?

2024-09-22 09:38 UTC, ievetrovdev commented
> При клике на категорию не открывает экран со списком рецептов, что я не доделал?

Ты сделал всё правильно, открывается нужный экран, просто на нём ничего не отображается. Можешь добавить логгирование и глянуть, что все приходит корректно. В следующем задании мы будем реализовывать, чтоб эти данные уже отображались на экране

2024-09-22 09:41 UTC, ievetrovdev requested changes

2024-09-22 09:41 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/CategoriesListFragment.kt
> +            "ARG_CATEGORY_ID" to categoryId,
Кючи для аргументов принято выносить как общие константы проекта в отдельный файл. Его можно назвать, например, Constants.kt и переиспользовать оттуда в разных местах, где это требуется.

2024-09-22 09:41 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/RecipesListFragment.kt
>          fun newInstance() = RecipesListFragment()
Бесполезный метод

2024-09-22 09:41 UTC, ievetrovdev commented on app/src/main/java/com/knyazev/recipesapp/CategoriesListFragment.kt
> +        val categoryImageUrl = STUB.getCategories()[categoryId].imageUrl
Здесь происходит двойное обращение к нашему импровизированному бэкенду. Предлагаю сразу мыслить оптимально и делать один запрос и уже здесь производить поиск нужной категории.

2024-09-24 18:35 UTC, ievetrovdev approved these changes

2024-09-26 03:42 UTC, merged