RA-11 Implements screen with list recipes
Artur-star/RecipesApp pull request #9
Opened 2024-10-07 13:28 UTC by Artur-star

2024-10-07 13:29 UTC, Artur-star commented
Запутался, помоги разобраться

2024-10-07 13:31 UTC, Artur-star commented
Почему не видно шапку Recipes при переходе на данный фрагмент

2024-10-09 06:01 UTC, ievetrov requested changes

2024-10-09 06:01 UTC, ievetrov commented on app/src/main/res/values/dimens.xml
>      <dimen name="padding_header_name_10">10dp</dimen>
Обращаю внимание на дублирование значений отступов

2024-10-09 06:01 UTC, ievetrov commented on app/src/main/java/com/knyazev/recipesapp/fragments/RecipesListFragment.kt
> +        categoryName = requireArguments().getString(ARG_CATEGORY_NAME)
Шапка не показывается, потому, что никак не устанавливаешь для нее изображение и название категории. То есть вот тут, например, имя получаешь. А нужной вью никак не присваиваешь. То же самое и с изображением.

2024-10-09 08:27 UTC, Artur-star commented
методы  openRecipeByRecipeId(recipeId: Int) и setOnItemClickListener(listener: OnItemClickListener) у меня нигде не используются, так и должно  быть на этом этапе?

2024-10-09 16:54 UTC, ievetrovdev commented
Нет, они должны уже работать также, как и в категориях. Глянь 7 пункт внимательнее
<img width="928" alt="Снимок экрана 2024-10-09 в 19 54 07" src="https://github.com/user-attachments/assets/0744e367-b536-449f-94c1-6e8e44f1266f">

2024-10-10 20:12 UTC, ievetrovdev approved these changes
Всё верно! Молодец!

2024-10-11 07:21 UTC, merged